apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: PORT
            - name: FILES_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: FILES_SERVICE_HOST
            - name: FILES_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: FILES_SERVICE_PORT
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: EMAIL
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: EMAIL_PASSWORD
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: JWT_REFRESH_SECRET
            - name: JWT_ACCESS_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: JWT_ACCESS_EXPIRATION_TIME
            - name: JWT_REFRESH_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: JWT_REFRESH_EXPIRATION_TIME
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: BASIC_AUTH_USERNAME
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: BASIC_AUTH_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gateway-mono-production-config-secret
                  key: DATABASE_URL
